<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <Import Project="..\..\properties\service_fabric_managed_common.props" />
  <ItemGroup>
    <PackageReference Include="Fuzzy" />
    <PackageReference Include="Inspector" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Diagnostics\Microsoft.ServiceFabric.Diagnostics.csproj" />
    <ProjectReference Include="..\TestFramework\Microsoft.ServiceFabric.TestFramework.csproj" />
  </ItemGroup>
</Project>
