<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;net8.0</TargetFrameworks>
    <Description>ASP.NET Core configuration provider that reads settings from Service Fabric configuration packages.</Description>
  </PropertyGroup>
  <Import Project="..\..\properties\service_fabric_managed_common.props" />
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" Condition="'$(TargetFramework)' != 'net462'" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Condition="'$(TargetFramework)' == 'net462'" />
    <PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Services\Microsoft.ServiceFabric.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="SR.resx" StronglyTypedLanguage="CSharp" />
  </ItemGroup>
</Project>
