<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <Import Project="..\..\properties\service_fabric_managed_common.props" />
  <ItemGroup>
    <PackageReference Include="Fuzzy" />
    <PackageReference Include="Inspector" />
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Actors\Microsoft.ServiceFabric.Actors.csproj" />
    <ProjectReference Include="..\TestFramework\Microsoft.ServiceFabric.TestFramework.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <Compile Remove="**\*.cs" />
    <Compile Include="ActorEventSourceTest.cs" />
    <Compile Include="AssemblyInfo.cs" />
    <Compile Include="Client\ActorProxyEventExtensionsTest.cs" />
    <Compile Include="Client\ActorProxyFactoryTest.cs" />
    <Compile Include="Client\ActorProxyTest.cs" />
    <Compile Include="Client\ActorServiceProxyTest.cs" />
    <Compile Include="Client\IFactoryTestActor.cs" />
    <Compile Include="Client\SubscriberTest.cs" />
    <Compile Include="ExceptionConvertors\Client\FabricActorExceptionConvertorTest.cs" />
    <Compile Include="ExceptionConvertors\Runtime\FabricActorExceptionConvertorTest.cs" />
    <Compile Include="IFuzzExtensions.cs" />
    <Compile Include="Remoting\ActorDataContractSurrogateTest.cs" />
    <Compile Include="Remoting\ActorLogicalCallContextTest.cs" />
    <Compile Include="Remoting\ActorRemotingProviderAttributeTest.cs" />
  </ItemGroup>
</Project>
