<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Microsoft.ServiceFabric</RootNamespace>
    <TargetFrameworks>net8.0;net472</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <Import Project="..\..\properties\service_fabric_managed_common.props" />
  <ItemGroup>
    <PackageReference Include="Fuzzy" />
    <PackageReference Include="Inspector" />
    <PackageReference Include="Microsoft.ServiceFabric" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit.v3.assert" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Constants\Microsoft.ServiceFabric.Constants.csproj" />
    <ProjectReference Include="..\..\src\Diagnostics\Microsoft.ServiceFabric.Diagnostics.csproj" />
  </ItemGroup>
</Project>
