<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;netstandard2.0</TargetFrameworks>
    <!--
      PowerShell modules have different folder structure than NuGet packages. Also, even though they can be downloaded
      from PSGallery as .nupkg files, the Publish-Module command requires a directory path instead of a package file.
      We use the built-in NuGet.Build.Tasks.Pack.targets to prepare a directory suitable for publishing the module.
      https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#advanced-extension-points-to-create-customized-package
    -->
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);GetFrameworkSpecificPowerShellModuleFiles</TargetsForTfmSpecificContentInPackage>
    <!-- 
      We still create a .nupkg for re-packaging of this module in the WindowsFabric repo with DSTS support for SAWDrop.
      This is not a valid NuGet package, so we need to disable some options and checks.
    -->
    <IncludeBuildOutput>false</IncludeBuildOutput> <!-- Don't create standard lib folder in the package -->
    <NoWarn>$(NoWarn);NU5100</NoWarn> <!-- Disable warnings assemblies not inside the lib folder -->
    <NoWarn>$(NoWarn);NU5128</NoWarn> <!-- Disable warnings about mismatch between target frameworks and folder names -->
    <!-- Don't generate a symbols package. ADO feeds don't support them and the internal pipeline publishes symbols directly from bin. -->
    <IncludeSymbols>false</IncludeSymbols>
    <Description>PowerShell module for managing Service Fabric clusters, applications, and services over HTTP.</Description>
  </PropertyGroup>
  <Import Project="..\..\properties\service_fabric_managed_common.props" />
  <ItemGroup>
    <ProjectReference Include="..\Client.Http\Microsoft.ServiceFabric.Client.Http.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Client"/>
    <PackageReference Include="Microsoft.Win32.Registry" />
    <PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="PowerShellStandard.Library" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="..\..\refs\SfSbzYamlMergeLib.dll" />
    <Reference Include="..\..\refs\Microsoft.ServiceFabric.YamlUtils.dll" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Resource.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemDefinitionGroup>
    <Content>
      <Pack>false</Pack> <!-- Don't pack unsigned content files -->
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory> <!-- for signing -->
    </Content>
  </ItemDefinitionGroup>
  <ItemGroup>
    <Content Link="Microsoft.ServiceFabric.Powershell.Http.psd1" Include="manifest\Microsoft.ServiceFabric.Powershell.Http.psd1" />
    <Content Link="Microsoft.ServiceFabric.Powershell.Http.Format.ps1xml" Include="Generated\psxml\Microsoft.ServiceFabric.Powershell.Http.Format.ps1xml" />
    <Content Link="Microsoft.ServiceFabric.Powershell.Http-Help.xml" Include="Generated\psxml\Microsoft.ServiceFabric.Powershell.Http-Help.xml" />
  </ItemGroup>

  <Target Name="PublishAllDependenciesAfterBuildForSigning" AfterTargets="Build" DependsOnTargets="Publish" Condition="'$(TargetFramework)' != ''" />

  <Target Name="DonNotBuildReferencesWhenPackingSignedFiles" BeforeTargets="ResolveProjectReferences" Condition="'$(_IsPacking)' == 'true'">
    <PropertyGroup>
      <BuildProjectReferences>false</BuildProjectReferences>
    </PropertyGroup>
  </Target>

  <Target Name="GetFrameworkSpecificPowerShellModuleFiles" Outputs="@(TfmSpecificPackageFile)" DependsOnTargets="PublishItemsOutputGroup">
    <PropertyGroup>
      <PowerShellFramework Condition="'$(TargetFramework)' == 'netstandard2.0'">netstandard</PowerShellFramework>
      <PowerShellFramework Condition="'$(TargetFramework)' == 'net462'">netframework</PowerShellFramework>
    </PropertyGroup>
    <ItemGroup>
      <TfmSpecificPackageFile Include="@(PublishItemsOutputGroupOutputs->'%(OutputPath)')" PackagePath="$(PowerShellFramework)"
        Condition="'%(PublishItemsOutputGroupOutputs.ExcludeFromSingleFile)' != 'true' and '%(PublishItemsOutputGroupOutputs.Extension)' != '.psd1'" />
    </ItemGroup>
  </Target>

  <Target Name="CopyPowerShellModuleToOutputPath" BeforeTargets="GenerateNuSpec" DependsOnTargets="$(GenerateNuspecDependsOn)">
    <PropertyGroup>
      <ModuleOutputPath>$(PackageOutputPath)$(PackageId).$(PackageVersion)</ModuleOutputPath>
    </PropertyGroup>
    <ItemGroup>
      <_PackageFiles Include="$(OutputPath)net462\Microsoft.ServiceFabric.Powershell.Http.psd1" PackagePath="/" />
    </ItemGroup>
    <Copy SourceFiles="@(_PackageFiles)" DestinationFiles="@(_PackageFiles->'$(ModuleOutputPath)\%(PackagePath)\%(Filename)%(Extension)')" />
  </Target>
</Project>
