//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.ServiceFabric.Powershell.Http {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.ServiceFabric.Powershell.Http.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of ServerCommonNames must match count of IssuerCertThumbprints if provided..
        /// </summary>
        internal static string CommonNameIssuerThumbprintMismatch {
            get {
                return ResourceManager.GetString("CommonNameIssuerThumbprintMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error_MissingImageStoreConnectionStringArgument.
        /// </summary>
        internal static string Error_MissingImageStoreConnectionStringArgument {
            get {
                return ResourceManager.GetString("Error_MissingImageStoreConnectionStringArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while getting access token from Azure Active Directory..
        /// </summary>
        internal static string ErrorAAD {
            get {
                return ResourceManager.GetString("ErrorAAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format of connection endpoint is incorrect..
        /// </summary>
        internal static string ErrorIncorrectEndpointFormat {
            get {
                return ResourceManager.GetString("ErrorIncorrectEndpointFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load client certificate based on provided inforamtion..
        /// </summary>
        internal static string ErrorLoadingClientCertificate {
            get {
                return ResourceManager.GetString("ErrorLoadingClientCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting with IP Address. provide value for at least one of ServerCommonName or ServerCertThumbprint...
        /// </summary>
        internal static string ErrorNoServerCommonNameIrServerCertThumbprint {
            get {
                return ResourceManager.GetString("ErrorNoServerCommonNameIrServerCertThumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to Service Fabric cluster, please connect using Connect-SFCluster cmdlet before invoking this cmdlet..
        /// </summary>
        internal static string ErrorNotConnected {
            get {
                return ResourceManager.GetString("ErrorNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster connection with the same name already existed, the old connection will be deleted.
        /// </summary>
        internal static string Info_ClusterConnectionAlreadyExisted {
            get {
                return ResourceManager.GetString("Info_ClusterConnectionAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Active Directory sign in is required to get access token required to connect to cluster..
        /// </summary>
        internal static string MsgAADSignin {
            get {
                return ResourceManager.GetString("MsgAADSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding property: {0} to result.
        /// </summary>
        internal static string MsgAddProperty {
            get {
                return ResourceManager.GetString("MsgAddProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected Successfully!.
        /// </summary>
        internal static string MsgConnectSuccess {
            get {
                return ResourceManager.GetString("MsgConnectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of data items retrieved:{0}; Continuation Token: {1}.
        /// </summary>
        internal static string MsgCountAndContinuationToken {
            get {
                return ResourceManager.GetString("MsgCountAndContinuationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not of type {0}, rather it is: {1}.
        /// </summary>
        internal static string MsgObjectTypeMismatch {
            get {
                return ResourceManager.GetString("MsgObjectTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition Info: {0}.
        /// </summary>
        internal static string MsgPartitionInfo {
            get {
                return ResourceManager.GetString("MsgPartitionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replica Info: {0}.
        /// </summary>
        internal static string MsgReplicaInfo {
            get {
                return ResourceManager.GetString("MsgReplicaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid resource type: {0} found in the yaml description, skipping it..
        /// </summary>
        internal static string WarningInvalidResourceType {
            get {
                return ResourceManager.GetString("WarningInvalidResourceType", resourceCulture);
            }
        }
    }
}
