<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="service_fabric_common.props" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform>AnyCPU</Platform>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <TreatWarningsAsErrors Condition=" '$(Configuration)' == 'Release' ">true</TreatWarningsAsErrors>
    <WarningLevel>4</WarningLevel>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <!-- Assembly name, title and documentation -->
  <PropertyGroup>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <AssemblyTitle>$(AssemblyName)</AssemblyTitle>
  </PropertyGroup>

  <!-- Properties specific to certain TargetFrameworks -->
  <PropertyGroup Condition="'$(TargetFramework)' == 'net462'">
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <!-- set DebugType to full -->
  <PropertyGroup>
    <DebugType>full</DebugType>
  </PropertyGroup>

  <!-- https://github.com/microsoft/binskim/blob/main/docs/BinSkimRules.md -->
  <PropertyGroup>
    <!-- https://learn.microsoft.com/dotnet/csharp/language-reference/compiler-options/security#highentropyva -->
    <HighEntropyVA>true</HighEntropyVA>
    <!-- https://learn.microsoft.com/dotnet/csharp/language-reference/compiler-options/advanced#checksumalgorithm -->
    <ChecksumAlgorithm>SHA256</ChecksumAlgorithm>
  </PropertyGroup>
  
  <!-- Enable delay signing with Key.snk -->
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
    <DelaySign>true</DelaySign>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)Key.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <!-- Use C# 11.0 features -->
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
  </PropertyGroup>

  <!-- Set Version numbers. These are used for generating Assemblies. -->
  <PropertyGroup>
    <AssemblyVersion>6.0.0.0</AssemblyVersion>
    <PackageVersionSuffix>-beta</PackageVersionSuffix>
    <Version>$(MajorVersion).$(MinorVersion).$(BuildVersion).$(Revision)$(PackageVersionSuffix)</Version>
    <AssemblyFileVersion>$(MajorVersion).$(MinorVersion).$(BuildVersion).$(Revision)</AssemblyFileVersion>
    <FileVersion>$(MajorVersion).$(MinorVersion).$(BuildVersion).$(Revision)</FileVersion>
  </PropertyGroup>

  <PropertyGroup>
    <Product>Microsoft Azure Service Fabric</Product>
    <Copyright>Copyright (c) Microsoft Corporation.  All rights reserved.</Copyright>
    <Company>Microsoft</Company>
    <Authors>Microsoft</Authors>
  </PropertyGroup>
</Project>
