//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.ServiceFabric.Client.Http.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.ServiceFabric.Client.Http.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AADTokenHandler cannot be created for SecuritySettings of type {0}.
        /// </summary>
        internal static string ErrorAADTokenHandlerIncorrectSecuritySettings {
            get {
                return ResourceManager.GetString("ErrorAADTokenHandlerIncorrectSecuritySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot refresh security settings before configuring security..
        /// </summary>
        internal static string ErrorCannotCallRefreshSecuritySettingsBeforeConfiguring {
            get {
                return ResourceManager.GetString("ErrorCannotCallRefreshSecuritySettingsBeforeConfiguring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change security type when refreshing security settings..
        /// </summary>
        internal static string ErrorCannotChangeSecurityType {
            get {
                return ResourceManager.GetString("ErrorCannotChangeSecurityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot configure security again, use RefreshSecuritySettings if intended to refresh settings..
        /// </summary>
        internal static string ErrorCannotConfigureSecurityAgain {
            get {
                return ResourceManager.GetString("ErrorCannotConfigureSecurityAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize json response from server..
        /// </summary>
        internal static string ErrorCanNotDeserializeResponseFromServer {
            get {
                return ResourceManager.GetString("ErrorCanNotDeserializeResponseFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimsTokenHandler cannot be created for SecuritySettings of type {0}.
        /// </summary>
        internal static string ErrorClaimsTokenHandlerIncorrectSecuritySettings {
            get {
                return ResourceManager.GetString("ErrorClaimsTokenHandlerIncorrectSecuritySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization error, invalid client credentials..
        /// </summary>
        internal static string ErrorClientCredentialsInvalid {
            get {
                return ResourceManager.GetString("ErrorClientCredentialsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided collection cannot be empty..
        /// </summary>
        internal static string ErrorCollectionCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrorCollectionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection has already been opened..
        /// </summary>
        internal static string ErrorConnectionAlreadyOpened {
            get {
                return ResourceManager.GetString("ErrorConnectionAlreadyOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection has been closed or has not been opened..
        /// </summary>
        internal static string ErrorConnectionClosed {
            get {
                return ResourceManager.GetString("ErrorConnectionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an object of type &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorExpectedObjectOfTypeFormatString {
            get {
                return ResourceManager.GetString("ErrorExpectedObjectOfTypeFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The generic parameter &apos;{0}&apos; is not an enum type..
        /// </summary>
        internal static string ErrorGenericParameterNotAnEnumFormatString {
            get {
                return ResourceManager.GetString("ErrorGenericParameterNotAnEnumFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}&apos; was unsuccessful: \n{1} - {2}\n{3}.
        /// </summary>
        internal static string ErrorHttpOperationUnsuccessfulFormatString {
            get {
                return ResourceManager.GetString("ErrorHttpOperationUnsuccessfulFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error making Http request..
        /// </summary>
        internal static string ErrorHttpRequestException {
            get {
                return ResourceManager.GetString("ErrorHttpRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Validation callback is valid when server url is https..
        /// </summary>
        internal static string ErrorIncorrectCredentialTypeForValidateCertificate {
            get {
                return ResourceManager.GetString("ErrorIncorrectCredentialTypeForValidateCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid client client credentials, call will be retried with rereshed security settings..
        /// </summary>
        internal static string ErrorInvalidClientCredentialsRetryMessage {
            get {
                return ResourceManager.GetString("ErrorInvalidClientCredentialsRetryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json returned from server is invalid .
        /// </summary>
        internal static string ErrorInvalidJsonInResponse {
            get {
                return ResourceManager.GetString("ErrorInvalidJsonInResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid resource uri {0}.
        /// </summary>
        internal static string ErrorInvalidResourceUri {
            get {
                return ResourceManager.GetString("ErrorInvalidResourceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource/content/path does not exist on the server..
        /// </summary>
        internal static string ErrorMessageHTTP404 {
            get {
                return ResourceManager.GetString("ErrorMessageHTTP404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handlers specified in delegate handlers list cannot be null..
        /// </summary>
        internal static string ErrorNullDelegateHandler {
            get {
                return ResourceManager.GetString("ErrorNullDelegateHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null response received from server for the request..
        /// </summary>
        internal static string ErrorNullResponse {
            get {
                return ResourceManager.GetString("ErrorNullResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the provided partition key &apos;{0}&apos; for service &apos;{1}&apos;.
        /// </summary>
        internal static string ErrorPartitionKeyNotFoundFormatString {
            get {
                return ResourceManager.GetString("ErrorPartitionKeyNotFoundFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid client client certificate, call will be retried with rereshed security settings..
        /// </summary>
        internal static string ErrorRemoteCertValidationFailureRetryMessage {
            get {
                return ResourceManager.GetString("ErrorRemoteCertValidationFailureRetryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote certificate is invalid according to the validation procedure..
        /// </summary>
        internal static string ErrorRemoteServerCertValidation {
            get {
                return ResourceManager.GetString("ErrorRemoteServerCertValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server timeout must be greater than zero..
        /// </summary>
        internal static string ErrorTimeoutOutOfRange {
            get {
                return ResourceManager.GetString("ErrorTimeoutOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to use the HTTP connection..
        /// </summary>
        internal static string ErrorUnableToBeginRequest {
            get {
                return ResourceManager.GetString("ErrorUnableToBeginRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find endpoints for {0}. Please make the call to resolve service partition again..
        /// </summary>
        internal static string ErrorUnableToFindEndpointForChosenRole {
            get {
                return ResourceManager.GetString("ErrorUnableToFindEndpointForChosenRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the &apos;{0}&apos; property on object &quot;{1}&quot;..
        /// </summary>
        internal static string ErrorUnableToFindKindPropertyFormatString {
            get {
                return ResourceManager.GetString("ErrorUnableToFindKindPropertyFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine what kind of object is being deserialized. Kind value &apos;{0}&apos; not found..
        /// </summary>
        internal static string ErrorUnableToLookupKindFormatString {
            get {
                return ResourceManager.GetString("ErrorUnableToLookupKindFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to look up listener named &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorUnableToLookUpListenerFormatString {
            get {
                return ResourceManager.GetString("ErrorUnableToLookUpListenerFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster http management endpoint url scheme doesn&apos;t match with SecuritySettings type. Url scheme is {0}, expected as per security settings is {1}..
        /// </summary>
        internal static string ErrorUrlScheme {
            get {
                return ResourceManager.GetString("ErrorUrlScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server returned error while processing the request, but did not provide a meaningful error response. Response Error Code {0}.
        /// </summary>
        internal static string ServerErrorNoMeaningFulResponse {
            get {
                return ResourceManager.GetString("ServerErrorNoMeaningFulResponse", resourceCulture);
            }
        }
    }
}
