#
# Module manifest for module 'PSGet_Microsoft.ServiceFabric.Powershell.Http'
#
# Generated by: Microsoft Corporation
#
# Generated on: 12/4/2018
#

@{

# Script module or binary module file associated with this manifest.
    RootModule = if($PSEdition -eq 'Core')
    {
        'netstandard\Microsoft.ServiceFabric.Powershell.Http.dll'
    }
    else # Desktop
    {
        'netframework\Microsoft.ServiceFabric.Powershell.Http.dll'
    }

# Version number of this module. Minor.Patch version matches the Major.Minor version of client lib.
ModuleVersion = '1.10.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '8bb27e21-0e75-41c6-98d2-d44db181cd5f'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = '(c) 2018 Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Powershell cmdlets to manage a Service Fabric Cluster.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess = if($PSEdition -eq 'Core')
    {
        'netstandard\Microsoft.ServiceFabric.Powershell.Http.Format.ps1xml'
    }
    else # Desktop
    {
        'netframework\Microsoft.ServiceFabric.Powershell.Http.Format.ps1xml'
    }

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'ServiceFabric'

        # A URL to the license for this module.
        LicenseUri = 'http://www.microsoft.com/web/webpi/eula/net_library_eula_ENU.htm'

        # A URL to the main website for this project.
        ProjectUri = 'http://github.com/microsoft/service-fabric-client-dotnet'

        # A URL to an icon representing this module.
        IconUri = 'http://go.microsoft.com/fwlink/?LinkID=288890'

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        Prerelease = 'preview1'

        # Flag to indicate whether the module requires explicit user acceptance for install/update
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

