<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net462</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>Reliable Actors framework for building lightweight, single-threaded stateful objects on Service Fabric.</Description>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);PackageContent</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>
  <Import Project="..\..\properties\service_fabric_managed_common.props" />
  <ItemGroup>
    <PackageReference Include="Microsoft.ServiceFabric" />
    <PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Constants\Microsoft.ServiceFabric.Constants.csproj" PrivateAssets="All" />
    <ProjectReference Include="..\Diagnostics\Microsoft.ServiceFabric.Diagnostics.csproj" />
    <ProjectReference Include="..\Services.Remoting\Microsoft.ServiceFabric.Services.Remoting.csproj" />
    <ProjectReference Include="..\Services\Microsoft.ServiceFabric.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="SR.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SR.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="SR.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SR.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Content Include="build/**" PackagePath="build" />
  </ItemGroup>
  <Target Name="PackageContent" Outputs="@(TfmSpecificPackageFile)">
    <MSBuild Projects="..\FabActUtil\FabActUtil.csproj" Targets="BuiltProjectOutputGroup">
      <Output TaskParameter="TargetOutputs" ItemName="FabActUtilIntermediateOutput" />
    </MSBuild>
    <ItemGroup>
      <TfmSpecificPackageFile Include="@(FabActUtilIntermediateOutput->'%(FinalOutputPath)')">
        <PackagePath>build\$(TargetFramework)</PackagePath>
      </TfmSpecificPackageFile>
    </ItemGroup>
  </Target>
</Project>
