//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.ServiceFabric.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.ServiceFabric.Client.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster endpoint is not provided. Collection must have atleast one endpoint..
        /// </summary>
        internal static string ErrorClusterEndpointNotProvided {
            get {
                return ResourceManager.GetString("ErrorClusterEndpointNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSTS option is not supported in the current configuration. Its supported only in internal Service Fabric tooling drops..
        /// </summary>
        internal static string ErrorDstsNotSupported {
            get {
                return ResourceManager.GetString("ErrorDstsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service replica did not publish an address for listener with name name &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorListenerNotFound {
            get {
                return ResourceManager.GetString("ErrorListenerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Service Fabric object has been closed. Attempting to use the object after it has been closed is not allowed..
        /// </summary>
        internal static string ErrorServiceFabricObjectClosed {
            get {
                return ResourceManager.GetString("ErrorServiceFabricObjectClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Service Fabric object has not been opened..
        /// </summary>
        internal static string ErrorServiceFabricObjectNotOpen {
            get {
                return ResourceManager.GetString("ErrorServiceFabricObjectNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster endpoint in collection cannot be null..
        /// </summary>
        internal static string ErrorUrlCannotBeNull {
            get {
                return ResourceManager.GetString("ErrorUrlCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster http management endpoint url scheme doesnt match with SecuritySettings type. Url scheme is {0}, expected as per security settings is {1}..
        /// </summary>
        internal static string ErrorUrlScheme {
            get {
                return ResourceManager.GetString("ErrorUrlScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All management endponts must have same url scheme.
        /// </summary>
        internal static string ErrorUrlSchemeMismatch {
            get {
                return ResourceManager.GetString("ErrorUrlSchemeMismatch", resourceCulture);
            }
        }
    }
}
