<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net462</TargetFrameworks>
    <Description>Remoting APIs for type-safe RPC communication between Service Fabric services.</Description>
  </PropertyGroup>
  <Import Project="..\..\properties\service_fabric_managed_common.props" />
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Constants\Microsoft.ServiceFabric.Constants.csproj" PrivateAssets="All" />
    <ProjectReference Include="..\FabricTransport\Microsoft.ServiceFabric.FabricTransport.csproj" />
    <ProjectReference Include="..\Diagnostics\Microsoft.ServiceFabric.Diagnostics.csproj" />
    <ProjectReference Include="..\Services\Microsoft.ServiceFabric.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="SR.resx" StronglyTypedLanguage="CSharp" />
  </ItemGroup>
</Project>
