<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net462</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <Import Project="..\..\properties\service_fabric_managed_common.props" />
  <PropertyGroup>
    <!-- 
      The netframework.targets expects FabActUtil to be an EXE. The netcore.targets expects FabActUtil to be a DLL.
      The netcore binary cannot be an EXE because the SF.ActorsServices.Internal package reference fails to resolve the DLL with the same name.
    -->
    <OutputType Condition="'$(TargetFramework)' == 'net462'">Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Actors\Microsoft.ServiceFabric.Actors.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="SR.resx" StronglyTypedLanguage="CSharp" />
  </ItemGroup>
</Project>
