<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!-- TODO Fix https://aka.ms/aspnet/deprecate/008 and remove -->
    <WarningsNotAsErrors>ASPDEPR008</WarningsNotAsErrors>
  </PropertyGroup>
  <Import Project="..\..\properties\service_fabric_managed_common.props" />
  <ItemGroup Condition="'$(TargetFramework)' != 'net472'">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <PackageReference Include="Microsoft.Extensions.Logging.Console"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="Moq"/>
    <PackageReference Include="xunit.runner.visualstudio"/>
    <PackageReference Include="xunit.v3"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\AspNetCore.Configuration\Microsoft.ServiceFabric.AspNetCore.Configuration.csproj" />
    <ProjectReference Include="..\..\src\AspNetCore.HttpSys\Microsoft.ServiceFabric.AspNetCore.HttpSys.csproj" />
    <ProjectReference Include="..\..\src\AspNetCore.Kestrel\Microsoft.ServiceFabric.AspNetCore.Kestrel.csproj" />
    <ProjectReference Include="..\..\src\Services\Microsoft.ServiceFabric.Services.csproj" />
  </ItemGroup>
</Project>
