<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <!--
      This project merged into a single assembly three projects/assemblies that were defined separately in
      https://github.com/microsoft/service-fabric-client-dotnet
      - Microsoft.ServiceFabric.Common
      - Microsoft.ServiceFabric.Client
      - Microsoft.ServiceFabric.Client.Http

      Unfortunately, the original code in these projects wasn't ready to be shipped in a stable NuGet package version.
      On the other hand, the Microsoft.ServiceFabric.Common and Microsoft.ServiceFabric.Client names are needed for
      migration of the code from the System.Fabric assembly. Because the Microsoft.ServiceFabric.Client.Http NuGet
      package included all three assembly, we can safely combine their code in the Microsoft.ServiceFabric.Client.Http.dll.
    -->
    <RootNamespace>Microsoft.ServiceFabric</RootNamespace>
    <Description>HTTP client APIs for managing Service Fabric clusters, applications, services, and resources.</Description>
  </PropertyGroup>
  <Import Project="..\..\properties\service_fabric_managed_common.props" />
  <ItemGroup>
    <ProjectReference Include="..\Constants\Microsoft.ServiceFabric.Constants.csproj" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="SR.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SR.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="SR.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SR.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>  
</Project>
