name: build

on: 
  push:
    branches:
      - develop
      - 'release_*'
    
  pull_request:
    branches: 
    - develop
    - 'release_*'

permissions:
  contents: read

env:
  Configuration: Release
  Artifacts: ${{ github.workspace }}/out
  Logs: ${{ github.workspace }}/out/logs

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - run: .\SkipStrongName.ps1
      - run: .\UninstallSfSdkFromGac.ps1
      - run: dotnet build -bl:"$env:Logs/build.binLog"
      - run: dotnet test --no-build --logger trx -bl:"$env:Logs/test.binLog"
      - run: dotnet pack --no-build -bl:"$env:Logs/pack.binLog"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-windows
          path: ${{ env.Artifacts }}

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: dotnet build -bl:"$Logs/build.binLog"
      - run: dotnet test --no-build --logger trx --framework net10.0 -bl:"$Logs/test.binLog"
      - run: dotnet pack --no-build -bl:"$Logs/pack.binLog"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-linux
          path: ${{ env.Artifacts }}
