name: build

on: 
  push:
    branches:
      - develop
      - 'release_*'
    
  pull_request:
    branches: 
    - develop
    - 'release_*'

permissions:
  contents: read

env:
  Configuration: Release
  Artifacts: ${{ github.workspace }}/out
  Logs: ${{ github.workspace }}/out/logs

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Windows environment
        if: runner.os == 'Windows'
        run: |
          .\eng\SkipStrongName.ps1
          .\eng\UninstallSfSdkFromGac.ps1
      - run: dotnet build -bl:"${{ env.Logs }}/build.binLog"
      - run: dotnet test --no-build --logger trx -bl:"${{ env.Logs }}/test.binLog"
      - run: dotnet pack --no-build -bl:"${{ env.Logs }}/pack.binLog"
      - uses: actions/upload-artifact@v6
        if: always()
        with:
          name: build-${{ matrix.os }}
          path: ${{ env.Artifacts }}
