name: Copilot Setup Steps

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  copilot-setup-steps:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - run: |
          .\eng\SkipStrongName.ps1
          .\eng\UninstallSfSdkFromGac.ps1
        shell: pwsh # CCA uses Bash on Windows by default
      - run: dotnet restore
