<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0;net472</TargetFrameworks>
    <RootNamespace>Microsoft.ServiceFabric.Data</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <Import Project="..\..\properties\service_fabric_managed_common.props" />
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Data.Interfaces.V2\Microsoft.ServiceFabric.Data.Interfaces.V2.csproj" />
  </ItemGroup>
</Project>
